server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notify-group
      auto-offset-reset: earliest
    template:
      default-topic: notify-topic

  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: YOUR_SES_SMTP_USERNAME
    password: YOUR_SES_SMTP_PASSWORD
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

notify:
  email:
    from: no-reply@example.com
